apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: "minio"
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:RELEASE.2017-11-22T19-55-46Z
        args:
        - server
        - http://minio-0.minio.imageresizer.svc.cluster.local/data
        - http://minio-1.minio.imageresizer.svc.cluster.local/data
        - http://minio-2.minio.imageresizer.svc.cluster.local/data
        - http://minio-3.minio.imageresizer.svc.cluster.local/data
        ports:
        - containerPort: 9000
          name: minio
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi