## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: minio
  clusterIP: None
  selector:
    app: minio