apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-api-deployment
  labels:
    app: image-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-api
  template:
    metadata:
      labels:
        app: image-api
    spec:
      containers:
      - name: image-api 
        image: postgrest/postgrest
        env:
        - name: PGRST_DB_URI
          value: "postgres://supinfo:supinfo@10.98.240.92:5432/images"
        - name: PGRST_DB_ANON_ROLE
          value: web_anon
        - name: PGRST_DB_SCHEMA
          value: api 
        ports:
        - containerPort: 3000 
