apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobs-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jobs-api.name" . }}
    helm.sh/chart: {{ include "jobs-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jobs-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jobs-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api_port }} 
              protocol: TCP
          env:
            - name: API_PORT
              value: "{{ .Values.api_port }}"
            - name: STORAGE_BUCKETNAME
              value: "{{ .Values.storage.bucketname }}"
            - name: STORAGE_SERVER
              value: "{{ .Values.storage.server }}"
            - name: STORAGE_PORT
              value: "{{ .Values.storage.port }}"
            - name: STORAGE_ACCESSKEY
              value: "{{ .Values.storage.accesskey }}"
            - name: STORAGE_SECRETKEY
              value: "{{ .Values.storage.secretkey }}"
            - name: STORAGE_SSL
              value: "{{ .Values.storage.ssl }}"
            - name: NATS_CONNECTIONSTRINGS
              value: "{{ .Values.nats.connectionstrings }}"
            - name: NATS_QUEUE
              value: "{{ .Values.nats.queue }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
